apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_URLS: http://+:80;http://+:7050
  RabbitMQ__Host: rabbitmq-clusterip
  ConnectionStrings__Redis: redis-cache
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7050
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: http://+:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbitmq-clusterip
  AuctionServiceUrl: http://auction-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbitmq-clusterip
  GrpcAuction: http://auction-clusterip:7050
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMQ__Host: rabbitmq-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  Cors_Allowed_Origins: https://app.carsties.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
  KC_DB: postgres
  KC_PROXY: edge
  KC_HOSTNAME: https://id.carsties.local
  KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-svc-config
data:
  AUTH_URL: https://app.carsties.local
  AUTH_URL_INTERNAL: http://webapp-clusterip:3000
  API_URL: http://gateway-clusterip
  ID_URL: https://id.carsties.local
  ID_URL_INTERNAL: http://identity-clusterip
  NOTIFY_URL: https://api.carsties.local/notification